//%attributes = {"invisible":true}
/*

export v1/batch endpoint batch request
used to generate training dataset

*/

//prompts were also generated by Claude
var $folder : 4D:C1709.Folder
$folder:=Folder:C1567("/DATA/prompts/queries")
var $systemPrompt; $userPrompt; $userPromptTemplate : Text
$systemPrompt:=$folder.file("system.txt").getText()
$userPromptTemplate:=$folder.file("user.txt").getText()

var $jsonl : Object
$jsonl:={requests: []}

var $passages : cs:C1710.PassageSelection
var $passage : cs:C1710.PassageEntity
var $languages : Collection
$languages:=["en"; "fr"]
$passages:=ds:C1482.Passage.query("document.meta.version == :1"+\
" and document.meta.language in :2"+\
" and searches == null"; "21-R2"; $languages)

var $provider : Text
$provider:="OpenAI"
//$provider:="Anthropic"

For each ($passage; $passages.slice(0; 3))
	var $language; $version; $text : Text
	$language:=$passage.document.meta.language
	$version:=$passage.document.meta.version
	$text:=$passage.text
	PROCESS 4D TAGS:C816($userPromptTemplate; $userPrompt; {text: $text; language: $language; version: $version})
	var $json : Object
	
	Case of 
		: ($provider="Anthropic")
			$json:={params: {}}
			$json.custom_id:="passage-"+String:C10($passage.getKey())
			$json.params.model:="claude-sonnet-4-6"
			$json.params.max_tokens:=1500
			$json.params.system:=$systemPrompt
			$json.params.messages:=[{role: "user"; content: $userPrompt}]
			$jsonl.requests.push($json)
		: ($provider="OpenAI")
			$json:={body: {}}
			$json.custom_id:="passage-"+String:C10($passage.getKey())
			$json.method:="POST"
			$json.url:="/v1/chat/completions"
			$json.body.model:="gpt-5.4"
			$json.body.model:="gpt-5.4-mini"
			$json.body.max_completion_tokens:=1500
			$json.body.messages:=[\
				{role: "system"; content: $systemPrompt}; \
				{role: "user"; content: $userPrompt}]
			$jsonl.requests.push(JSON Stringify:C1217($json))
	End case 
End for each 

Case of 
	: ($provider="Anthropic")
		Folder:C1567(fk desktop folder:K87:19).file($provider+"-batch-example.jsonl").setText(JSON Stringify:C1217($jsonl))
	: ($provider="OpenAI")
		Folder:C1567(fk desktop folder:K87:19).file($provider+"-batch-example.jsonl").setText($jsonl.requests.join("\n"))
End case 